//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "CONSUME_PRODT_KEYWORD_V1")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub consume_keyword_type: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub consume_keyword: String,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
    pub created_by: String,
    pub updated_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
