//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod consume_keyword_type_v1;
pub mod consume_prodt_detail;
pub mod consume_prodt_keyword;
pub mod consume_prodt_keyword_v1;
pub mod consumue_keyword_type;
pub mod users;
