//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::consume_keyword_type_v1::Entity as ConsumeKeywordTypeV1;
pub use super::consume_prodt_detail::Entity as ConsumeProdtDetail;
pub use super::consume_prodt_keyword::Entity as ConsumeProdtKeyword;
pub use super::consume_prodt_keyword_v1::Entity as ConsumeProdtKeywordV1;
pub use super::consumue_keyword_type::Entity as ConsumueKeywordType;
pub use super::users::Entity as Users;
